### ISSUE TITLE
Blade.Of().showFileList(true) works from IDE, but not from "java -jar"

### ISSUE THREAD

**Issue by andrea-ligios** [lets-blade/blade#314]
Given the code:

`Blade.of().showFileList(true).start();`

If the project is run from an IDE (in my case Eclipse 2018-09 under Ubuntu 18.04), opening http://localhost:9000/static/ shows the files within the static folder.

If the project is run with `java -jar app.jar`, it shows an empty page.

---

BONUS: It might also be an error [in the docs](https://lets-blade.com/docs/add-static-file.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%B5%84%E6%BA%90%E7%9B%AE%E5%BD%95), since it says the configuration attribute is `mvc.statics.list`;

[In the code](https://github.com/lets-blade/blade/blob/10bbb913bbe0e98e7fb70c502115b6134d45b5c2/src/main/java/com/blade/mvc/Const.java#L69) instead, I see `mvc.statics.show-list`

Cheers

**Comment by hellokaton** [comment]
@andrea-ligios  Thanks for your feedback, I have not noticed this problem before. In most cases, I packaged it in a directory instead of a separate jar.

This is a bug that occurs only when the resource file is packaged in a `jar` and accesses a directory, but accessing the files in `static` dir is fine.

I will fix it : )
